- name: Install Docker & Compose
  hosts: servers
  become: true
  become_method: sudo
  tasks:
    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Verify GPG key
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add user to docker group
      user:
        name: "{{ lookup('env', 'SSH_USER') }}"
        groups:
          - docker
        append: yes
      tags:
        - docker